Upgrade packages to prerelease versions of CanJS 6
The current error is below. can-simple-dom will need to be upgraded to
support HTMLElement.

ReferenceError: HTMLElement is not defined
    at DeriveElement (file:/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-stache-element/src/can-stache-element.js:48:38)
    at Object.<anonymous> (file:/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-stache-element/src/can-stache-element.js:107:44)
    at file:/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-stache-element/src/can-stache-element.js:109:4
    at file:/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-stache-element/src/can-stache-element.js:109:98
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at doEval (/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/steal/main.js:4788:10)
    at __eval (/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/steal/main.js:4892:7)
    at Loader.exec [as __exec] (/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/steal/main.js:2896:5)
    at load.metadata.execute (/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/steal/main.js:3869:13)
(node:51397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:51397) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Failed promise: TypeError: betweenTagsView is not a function
    at Constructor.setup (file:/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-component/can-component.js:676:21)
    at Function.newInstance (file:/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-construct/can-construct.js:307:22)
    at Constructor.init (file:/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-construct/can-construct.js:662:29)
    at new Constructor (eval at <anonymous> (evalmachine.<anonymous>:93:58), <anonymous>:3:34)
    at eval (file:/Users/josh/projects/bitovi/oss/donejs-chat/src/app.js!eval:52:15)
    at /Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-zone/lib/tasks.js:167:15
    at Task.run (/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-zone/lib/zone.js:39:17)
    at Zone.runTask (/Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-zone/lib/zone.js:184:14)
    at /Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-zone/lib/zone.js:285:15
    at /Users/josh/projects/bitovi/oss/donejs-chat/node_modules/can-zone/lib/tasks.js:178:21